name: Exercise_Workflow
on: [push]
jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: "Install style checker"
        run: pip install --upgrade pip black
      - name: "Run style check"
        run: |
          if ! black --check .; then 
          black .
          fi
      - name: "Verify"
        run: black --check . 

  test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: "Install dependencies"
        run: pip install --upgrade pip pytest pytest numpy matplotlib coverage
      - name: "Run tests with coverage"
        run: coverage run -m pytest
      - name: "Handover coverage package"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-package
          path: .coverage
          retention-days: 1
          include-hidden-files: true 

  coverage-report:  
      runs-on: ubuntu-latest
      needs: test
      steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: "Download coverage report"
        uses: actions/download-artifact@v4
        with:
          name: coverage-package
      - name: "Run coverage report"
        run: |
          coverage report
          coverage xml
      - name: "Upload coverage report"
        uses: actions/upload-artifact@v4
        with:
          files: ./coverage.xml
          retention-days: 14
  